### PR TITLE
fixed cob_console script

### PR DESCRIPTION
**Pull request by mathias-luedtke**
`cob_console.py` is not needed anymore..
Not sure if it is references somewhere else.

Should work for devel space and install space.

### CODE REVIEW

**Comment by floweisshardt** [comment]
cob_console.py was only used by cob_console. Please delete.

**Comment by floweisshardt** [comment]
Travis is complaining about install tags:
```
CMake Error at cob_command_tools/cob_script_server/cmake_install.cmake:125 (file):
  file INSTALL cannot find
  "/home/travis/catkin_ws/src/cob_command_tools/cob_script_server/src/cob_console.py".
```

@ipa-mdl: please fix install tags

**Comment by ipa-fxm** [comment]
FR ok

**Review by fmessmer — APPROVED** [review]
FR ok

**Pull request merged**
